---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.9.3
    env:
      TZ: "Europe/London"
    persistence:
      config:
        enabled: true
        existingClaim: homeassistant-config
    ingress:
      enabled: true
      ingressClassName: "traefik"
      host: "hassio.${SECRET_DOMAIN}"
      tlsSecret: "${SECRET_DOMAIN/./-}-tls"
      tls: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: "home-assistant"
        hajimari.io/instance: "internal"
        hajimari.io/appName: "HassIO"
        hajimari.io/group: "Home Automation"
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    resources:
      limits:
        memory: 500Mi
      requests:
        cpu: 35m
        memory: 150Mi