# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: pihole-secrets
    namespace: pihole
stringData:
    password: ENC[AES256_GCM,data:UYqQiywTToLv/TBO1QHRWKehCtsM,iv:Qb1YpHLz+6t2nvCVpBSuC9I8zfg33ktv/bHFflFxYNI=,tag:c/F94PDpKmPc0ccBerksZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-24T13:41:17Z"
    mac: ENC[AES256_GCM,data:UFmr/t6CukuGB3EBHHjbeZgM++eTC7QDZeC/NFqNWQGcRAEc26As9z9ZMe3ZBtmFtxzCXmlV23gBjqr8on4XD2JfzqhECUJJhBgwDhVNUzISbKCQl50dqSpJkk+wqsvEjFnP1mn9TuMLAr68YxZX4/FApZcGLcSGqZz2EfkwVoE=,iv:oXyM/6UZZZ1Qco57HvzMuTH+B7L3qgcghpwRSr3DrkY=,tag:QY53csbGK0bMngFD9zU74A==,type:str]
    pgp:
        - created_at: "2021-09-06T18:27:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxlXSe08L3iIARAAghrHWq5ZcnfsGzatT4lGE0lscByp51FI33za7yFskQ9b
            H763kUGqO8/qeXup9GRtQMwmSbUbfNx5ldLla4/kED3siWd9k6tv8In1pHDTfRXM
            ZoIH74OqObyRgXhuyZcKdQSYIgkSoDPK+rIU81ZEcrElUz2h8/RuLdTt2Yxtv8Qv
            1GKaTDx+2ympoVjab4wT+gdEjzpx+z0gCrPBZnw+gktaPuGSoYscH/e/9WMrfdTm
            Bao68HPkeJf/ZOkT7KCczfVjEwAWYgg7csMbIw7JwL3OGJ+9YmJfnVhTZv3/1kRH
            8NT4tujf+h6EtgeajHqZOyypqg/MM3Vjec2N5C4H+3ZnIZzCnmyL057vNkKMyPCu
            Ch/6XhHM5fbjV59FNMXd4nWk3teRBcS3KmJVQqEGqU1BhlrBwM3wyxFTTelucDgq
            IrTiAWrZKBfwakNy0FKaPYN+Q4ugri3FnIvx76ovzizlZgWfM/ATQgaK5PRs2hzS
            bWpbNuOUYL6M5tpcjPpHf9Vp8Vvb+ruKSO5vACpqL7wABFI6CDIgZLitwqn1SEbo
            28ioB4o9IcQHoNZGmNsfx5iZB+MuPML/udXAKY9tnvYSLXzYFYhXWDZTOoNtKlfR
            1p3k3B8cwI7UVRjyOINgm7P+qg/+d2sK4F2jA3GMTZSJ6oQd8+KSDuB0douqKl/S
            XgEIfo3Y3NZ4Yo+nucSU/4FamcIkPZ6XkrUEU42Ul+UhdZLSe4hlOjWS8n14GAdU
            KYJBvph8TYk/8qzzj81ZnRkrRMD+d83XktEbOKR5M/e8quNX3I8o5y7Ku2T/wyE=
            =vyLZ
            -----END PGP MESSAGE-----
          fp: D7E3AE409839E53D99E03033E3121149CD2C4A48
        - created_at: "2021-09-06T18:27:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwWz9VMtuJddARAAiNk5SNx6nZXvrAn0K6xAtwtUbhNDnM65zEV16V63283T
            0HS2Z9UpC1jHImfBKhEi3g6JPgC5IoF7D6XlGy05vtgBkOXUymdQH5npP1cg21l8
            kvm2GOaOQea+tNxgWlCNcHVX5yl72ryFtd4fxXxpfjsQUyxQmL8lQywgurHD+s/I
            OKoGYbF60CGHNbXTh//uJkbE1ZXyax0ztNwu9dQRsh7N+U9bqHLkFGZghUqGSveK
            c30yhAZyVDYNnk9877SR39PSs8e6gV4Ka0wjYhREBRzEwGcG4WLVNTeQGredWHsg
            PDKY7Z+b6slK1q5aIzp6qiNSY+dAaN8PtVpWpcxQdLgfzREb71F3ghSKSWVGYroz
            hAqGujCFCFNNfrM5zDFjnvpSSnu8lR4i/UlgoSBFCSdCA3h8pSQ5Y/ToasvLqRsU
            tlMRpLkFYXXMUjyC94KoS/g4XuENxjfsWsrpfHrJjYZ+M7MrGQkE1uVuj02N1lmB
            hNa+PjISE3kHVNnYEeSggWlmcFhG/stt1CyB6jOBQSmeKh+/D7+cYfMNkO8GGKJE
            Syak+t4Iv3Dxz8hSIy75kX8YiZObA3eGM95yDE5y70da62p2NkhwciMeISch62KN
            7qzAsLwGp4nTc24K73teNYeZS2exkIn6F3jE1aZxLmWUtnpvdx0MAcNZKWlPic/S
            XgH/j4YYFTOQBfOdFzfJgmqAz+3ub8GaRYCzi9cKQ4UshggdNxd1ZWflD+6aBXw9
            D6Zg3KFka7NEGjZa2Ten4MjVLcjmWYvdXqo9Rp9GGq6ZpT1c1AaMp1qRm408Xxo=
            =9owj
            -----END PGP MESSAGE-----
          fp: 6A26EC621F5482FA6A638E2A02E879357525DBCB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
