---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-charts.yaml
  - bootc.yaml
  - deliveryhero-charts.yaml
  - descheduler-charts.yaml
  - external-dns-charts.yaml
  - grafana-charts.yaml
  - hajimari-charts.yaml
  - infracloudio-charts.yaml
  - itstoni-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - longhorn-charts.yaml
  - metallb-charts.yaml
  - minio-charts.yaml
  - mojo2600.yaml
  - nfs-subdir-external-provisioner-charts.yaml
  - node-feature-discovery-charts.yaml
  - prometheus-community-charts.yaml
  - stakater-charts.yaml
  - traefik-charts.yaml
  - vmware-tanzu-charts.yaml
  - weaveworks-kured-charts.yaml
