---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasmoadmin-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
