---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tasmo-admin
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.itstoni.com/
      chart: tasmo-admin
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: itstoni-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: raymondmm/tasmoadmin
      tag: v1.7.0
    ingress:
      enabled: true
      path: /
      host: "tasmota.${SECRET_DOMAIN}"
      tls:
        - secretName: "${SECRET_DOMAIN/./-}-tls"
          host: "tasmota.${SECRET_DOMAIN}"
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: "home-automation"
        hajimari.io/appName: "Tasmo Admin"
    persistence:
      config:
        enabled: true
        existingClaim: tasmoadmin-data
        mountPath: "/data"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
