# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:k4RXO7Y56DCYPKZpog==,iv:0EfU18kk1ZuCp8XZwKZaIREq++W5yFfPt+F8nj6cCWo=,tag:NLByDcsdgxRVyHJjMQigTA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:CTEMlfdtK7T+5227yl5QT0etVu1MM9GT,iv:U2B2Lg04geK6VnwKDFczUMzxjOJVwb6UBd/ZlcEtuNk=,tag:9n7VJVTmFxw1LgQU5p/D8A==,type:str]
    SECRET_ALERT_MANAGER_SLACK_API_URL: ENC[AES256_GCM,data:DxYNGaWSziSDjQXXLyBGuVLCXaQal5SvY9vkdua2KN/38Yd/YEeqP6CD9Eh6uWC4BNhLaSyvegbrW2Je4Dsf9wcRg6X/DqpaUUDPfoHLrQ==,iv:PgxqTpTufrFwmLS4CRVj9TckYGlw+frAyfnVlgtvhLs=,tag:cGSsshvdU61BJjK/yqh0lw==,type:str]
    SECRET_LONGHORN_BACKUP_TARGET: ENC[AES256_GCM,data:YBKy+6P7Tt8aPUBWYPiNlJVbxJXWQEi1EE8C,iv:ljJCtnD5O7wA5WnLbSWmrZP7mqarfrQXyWPUBg+AISc=,tag:7iDgeKTKbtz+la8jLcMryw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-09T22:43:23Z"
    mac: ENC[AES256_GCM,data:fwDd5TgU+fbTT511z064JCmJBclb5OnUeUbR3H27KT6CcIekEP12njiRWzaHdFRKYXaDQlyrYjRY0PBEM9CNVv8O57iQq0QQgqy9+b4ge3R3p/6a0IA+61arpFpFzP4ty6OO3W8SawQt21QHUfD9kOBuaOLji8a0YRgK9c9ZtqY=,iv:cq7WJ5zkkxVm9q6FGKQVjCVlt5A8Xw15iicZbLDDtKI=,tag:PNdzufvb20wzUHccQlnibg==,type:str]
    pgp:
        - created_at: "2021-09-04T21:29:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxlXSe08L3iIAQ//U9INkiplVFxOMQGFzoAwbQ2Ac0e0F8xxD18464QGg0FW
            6V8KSksFv8ztNEvfTVpScBVN8EqGSW36IwGVGTLO0CNNX9fvsXgx1Qx1lcjJZZu+
            k5l41kW9vGJVNkSAKTkJ4bU+hpffg1b3X3hNY7mKIGlIddiYvcmfJYZngNna28V7
            n4BnW0+LDaidN3NtrwSexhtRV6h0cmyZrZYi5nZj1nmSS/MW+UdxkERaHc9+Z9LH
            wO5dDOz2L02l9QJNfHtm2X2lHGg6YppdaWJKedolG+By9bAVUi6zan75XnKooZCa
            k41PdYLUWKUCJJkQ8LhTS8tg/Is/R2tfImMNEnSokPBb8lsTDMCh3VTNjK05VOLV
            yq/bXHSLsv3BIq99LD+X+u79XAt+qLZ0PyhB25SGf4IfEuWMg1QGvnd0nRG3M4o4
            AkEuXZIe6GWOs6eCobuuxn7EVIndHIJDl2ZHG7P/CuoSPD5oF4HqUoYKRJ0L7E20
            qmCCSJi4C40QnNVTMFGT7U64DVod2CQ0bDLv99xzPi6xV5WmVtd/nL2007QA5Ag9
            lAzzgv5AL6SMH/q1wP1rvjWLPKpD4t383URL/J5QZv31S8hkJjcCVBQvobFdXdbF
            6RyMShG1J1n4Vi9CzfrKXXkktkQ+AE0lZhmTzNImS9ENv/i8ehTMJxJGfPpmYNzS
            XgHhz/d+eVhBVSvQu3u686d3MO9Aa3v/n/GvLmQZZT0vAvaShzgj108k8R7qVfCX
            gJgH/AnX6CnvfetWX0Gfgvc1cosf8jay7v2ARB/r0fet0SC6GB+KT8xch5UP9io=
            =4i63
            -----END PGP MESSAGE-----
          fp: D7E3AE409839E53D99E03033E3121149CD2C4A48
        - created_at: "2021-09-04T21:29:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwWz9VMtuJddAQ/+KZAyGGuNn6Fskw3QcsTMZhRSQnMBmC8FinUiDt8AldLm
            qkpqRp84GLc9mHtZ/WsTNwUI0PxkwzXnd3+zz8gd6d6o6jpeMgAIiQwjw+M6VnIH
            MpK7y4hGh2ZFk1Q+nv8vz6CO50OelhdusIZcR5aGHjFzGYinCOHv7haBFTAFwJjC
            bwAMUeGg6yYDlcZEcXeSMttLz7UcYbTkn9fTU6yADSxz37YZdf5yQmNYBzTQJcqj
            aB+r4EqbPji4xDITOL+ZMXH+HZa3q3smbwm+AplClwMVRVxFLzGKebXsqvCwM53+
            S4vpqTmBQubZHIGnA3sqy+d82pCdp4aGvoERfWcstqsxodBjFwZKRHYHleC5NUMv
            jSznG7wFc5ALYvgcpkvsUCwq/BxeptHHQBd3vwLSHkCpvRoPidTPIF9lyI8aiYRy
            YHcYWXTkR0ZS7V99W0sjQ3ec6n7sJdNlGir3X8ZVS3feE601TbfGf5hX6hrQob8k
            wVI0ti3UTIyA+74Ez+NzKcrh7TCLLMApTeVyAglGUc6qcFeiGDKSOcCWW+Gqf/Ng
            Oqjg4fNSbxheVlsQ4klTXn0N/vR4yBNVzBMV7j/GBALrh4jDWyBck3mVTs9z3JE2
            Lawnot9ac9s4SQBJpup1/StFRp6LmWDIIwHfNqmF4bQ2UNlZDhhvejthEEjoY43S
            XgGS2XXGYdnlwXkgebtS/4FE3V6OQCeSSOQLvNIP8rkO1mcaSD2uuO9EZrMOJ38T
            rlMW1kOOF+ZDYrTnAzkJK+LAF8D3g+ZfsyMLWGVjyLC7xqnRfoDeSYcnugq+IEs=
            =qh77
            -----END PGP MESSAGE-----
          fp: 6A26EC621F5482FA6A638E2A02E879357525DBCB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
