# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: longhorn-aws-creds
    namespace: longhorn-system
stringData:
    aws_access_key_id: ENC[AES256_GCM,data:O9IKpByl1HlkAszjLdk8ATCP47k=,iv:NP3ZLRvSVIXp+Q0BCekm8WwLyjpLZSp7wWKfjHF2Sow=,tag:n5C71rpO5y28z0cpKDESRw==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:9YyLTp5its9KUklb1FcqByPXysw1cijB1Cng01URK7Yh3TMiNPcS0A==,iv:Az0gYPeS1dV5V5BUwQ9SYItq7dHOHh/RSyivX22O6Uo=,tag:tAAI8XqrPLzih3AEEAL7Ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-09T22:07:11Z"
    mac: ENC[AES256_GCM,data:d8pLSGjmaEMRp7gDlHvcXTQZlOlUTLGr/OudToM52fbBsfPevAF8zRInIc9GbvhlyurMRaveolzORPHxkporSTU+sD83El37zPRpOXAy1ijjpwQbuhs2G9garEC5xtDQZXC8qDxYvj6AALNYaQgA9WFzBe9jbxw800W0mKw6T3c=,iv:7mIRGe8FQdU3/HO6g4AItTcD1Eb9I82PSH+cFH0NP0A=,tag:XN2GK39gn3M6gaDtMrXIFQ==,type:str]
    pgp:
        - created_at: "2021-09-09T22:07:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxlXSe08L3iIAQ//diG0Wbsv+JxPPgXx7AjOLPR03p/JyS2jD0Hg6Wfyhod8
            4TjfOHHm2dwIGRY05zo0mGg3fnitRqHunBM+OZfdKSJN/dhsnHAs8I+VkSHUkN9R
            txudckrqUyOmtmfexk+KVZ8iBkwsQZj/32Mrwy49zUhDjqqNRsZW8+pa0xq4Jz04
            OAR/MpBI11W/JRQTKI4RnwMAMMmLl2GZzM6mM+e+pfJW7tgukKdn+IR+rhQxkZsc
            pWXr2Lp5i1TDC0e/HOoigBfsrituvdqVuYbmIELIFzAq1vxRYvtkMfkPGcqwoZ1S
            VHird06QToUl3L4DhhYm6OwmQOgXAQHYUJ1Ob0hI5IjcqlRdcExC0w2eNFCY/kA1
            V+30zA4TF22+D/YaV8JJYlTjYccl+vtHiu1B3t/SULNnP70gDyrX3dYk2kAHtPTb
            IZvTGS8r7xxIWIW3XHxEoc8xrBMDIDnMYavYvns1fHKKvQoGCT5SFumDWe2h6aqh
            cZVBobrIRWRFUUFRVXryjUr62M8Pfh1qAKtMGBvKyf613H2pbbmFyHWTAEuaaa81
            SGNvImHOqVrjzDQyg9QkYhxnJeBasVHVe6dkyhyXlLgdRGT06BrkoY6rO3CLhZAq
            FE5ODoYiVNli/3lcGchGB7dOuW/VRaXNGx3GWLBoagfQ86/qXpLzYGARCT9PkH7S
            XgEQvNwwpbxu9atiE1Xl8TKfFAgZpZBMvawg9VQ56HmJcmzA6lLOm8JsE/ifk5WW
            atmDXRr6nLO9TFyccWXRhfal4jDG0IiIpQTeYhiHKoe/Im/k+bZ9T8nOcWutsuQ=
            =jhQA
            -----END PGP MESSAGE-----
          fp: D7E3AE409839E53D99E03033E3121149CD2C4A48
        - created_at: "2021-09-09T22:07:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwWz9VMtuJddARAAmKgPg6gRXmd4osGaCGINfbocbYxdIU/7ndY0fIotCCfJ
            JKU+f9q/Ux+9N4IP0VpDoBHYWzKGdDevl6Lpt+iyVkRpBTVfHmEaVbg2MwSlHeqL
            2/PRIU0KY5Maa3/lAo0I2ox1x4T0yXnV0ffTia2cXHYK3ezGSAPg0+dj2/aqv/u+
            PW+QS6H8dp49vpoucUbVQx23GG+a9D2HQghAmLUtCHLFe1UDWIXz5xY0ba0YC27M
            ll+IBTwU61Y4Wnke7XsCwQ/6QpfFV+D0hmclJdQV5yUwLcfCUQrh275fQXSzASJJ
            fHqhTpSveg7EpkDboNu710dubuI3Ir//6UGbXUBVzr175KNIvKr3PSOP++7JwW5i
            7oUh+bRvr6EMRVYIqLRLEpHLPOew9HH0ZS+PlFauV+WmxJSW76lycTQkiC+5t3qV
            tIFEpALqcAhFR+7ysGanzrn6wGMnst6hnmlYIgDdozlrss8rlJC+tlEXeaZWk9Vg
            FQCAIiP2G1n/MP7WmIx/hRmFSvNycIJdfQiKmAo4YlYfBmmwqCCqppVwfAS6vkgl
            lc07D0BCLRkNfiR4jr70rZixgv61qvNBPtKAv2OeLFQ93OnjR43SsnzjeguWjHnv
            aoHG/wLLQ6gU4BVhQ57y6C/VlSzMX4UHCzvArYlbOYgcQ0jzmPCgXPTEKJdceC7S
            XgFOyYwuSSekLuCQuIGzEzDvvXm1qfhdM+EsKU5XSh2ZxjIAOal/3TuXu9fmpQEZ
            cvFWV5WvIkAunnggLu5WFob+H0edQWsGx+Tb0hmEPvYhpvHr4xMKP/iCdNQFjeY=
            =Brlr
            -----END PGP MESSAGE-----
          fp: 6A26EC621F5482FA6A638E2A02E879357525DBCB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
