---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-data
  namespace: netbox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
