---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  releaseName: netbox
  chart:
    spec:
      # renovate: registryUrl=https://charts.boo.tc
      chart: netbox
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bootc-charts
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  test:
    enable: false
  values:
    existingSecret: netbox-secrets
    ingress:
      path: /
      enabled: true
      hosts:
        - host: netbox.${SECRET_DOMAIN}
      tls:
        - secretName: "${SECRET_DOMAIN/./-}-tls"
          hosts:
            - netbox.${SECRET_DOMAIN}
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: "netbox"

    persistence:
      enabled: true
      existingClaim: "netbox-data"
      
