# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: botkube-comms
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:9PhHmeBALnaZ5vnfr768Ri41K/nQFi9FrVoTormdPwP/mK0Oae3iteWgKDUARxUFG2IjIO+ObBYGbrrOoeMiE6wqiOniMAfgEYKysc4KLglP3NguAxvR/0Dk4w75VK7jl7WimYiRCwiA7b/k5BpS6Y91ToJu1E2y9+u4jRQnkdroQAvX23CRtqHNwcTMp3V+FpvwYXFidm2ttu3sZPnMe5wbWiKzoBNwY745VraLuIHUTdZiNdtvxgo02h3JPB26yyXWMjSM7nKwOGv8WbQh4Q==,iv:nv2Bjo7L4SCn+AChfFgrNiUOa2jPBChTZyjXkO0GthA=,tag:073v2VHav1uodw825iiNag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-06T11:53:48Z"
    mac: ENC[AES256_GCM,data:MIpdhkehtZmiyPt/242OFwrJhjlv/cNf66fg8N/4b3rJqKfnjj4VCB1CyLZYa+FXRf9nFHv8PdS8781mnqZNTYXK4pIQ8s7Yv89pFOecZFsfWQdNyrHjZ3i5dzyGs4Hdtc5QTvD1vUuzV4INoBmEn0Y2puHYo6TVAZbG9QfU460=,iv:UNBkJMxZf2QlF6OtCorCzXOeFvnwnk3Y3kxSyRBhGdo=,tag:BJrcWofAzhqqvLJH2m4hGA==,type:str]
    pgp:
        - created_at: "2021-09-06T11:53:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxlXSe08L3iIAQ//bJbM0lLtkp87Mi9KLuZiF8gTRKzxCW+EBwP/gL5FEAab
            RaicvKGMJJ404Fi+1BSIrW6APoOzC6eohnRYNDyQ/2zHDsU5Ro38/c7w6xM9+DTx
            3fE4JAkNpO1PoINIkt469ltNWuz1+bG2wrW5S8lDHblYvmrDYFATPQ6NgFF+PrGP
            27gaD4x+b8tB6/FnsUyOuarG+2I3VTS5fykTlwGCm8XcafPuK/PwTDk+xygYskcl
            E/Cl2JO5WBdM+GvrL7KMwZHXgcxJKcEFny+dRbuAe2VWy/B4C48DL42LKSctyenG
            QmlFZhq0aS+EBUEmzGZt/c4kaxaj2sL2a14sRn84xjW/Kh2aYYB3hplY04UMRXof
            GpXk9xLYdivkYM6atIdPNigonis14FRCYDvpthijdmMkZsq7IHNsh/uWCZSyoL4e
            ZPbzana+BD1Qu9gC3fSYPdACSMQ+AL3kIsq+Cu8Tx2L8J7VPR2ARAkgJaORZOaUW
            ww4cwS6sBO5hfEcaO65tRzYpjst8VoQL9RPrqfSw4y76yoc5urZ0x2LOW+YpNxgp
            Fojc/tf0lJweTU0mPIGCkg2iTmvssrFf3TOtHog6vbrLifChiPAblkWKQWHu2NSh
            hoiIIp702q5StsrOg4uQg/KQ7ZFxgE2zQZCokcKVDwX8Ruefoyo/ZaoolwVc0xXS
            XAHiWTHDIJ0bQJvgJNaEQypGnqeKdECS8d1nGfzKB0MwPtZmdyDmLBT4mNLQr68Q
            DOSajSZtQWD4zZc+pnJUEhEyuf7KCSYTcgeBrUT2WsKc5CYqMflgeOcUVuZv
            =pJCs
            -----END PGP MESSAGE-----
          fp: D7E3AE409839E53D99E03033E3121149CD2C4A48
        - created_at: "2021-09-06T11:53:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwWz9VMtuJddAQ//TMeVoWfCwWYKhK/eLM5auOpe/6PKGNPO+rmDqA1wl5/J
            WEkpceEGVBW/RddDnyPWiHm7p/J6eYynM5+GUeWUjtuYgtdjHSV3p3KiyUxugb6u
            9kcL1IQQje8HOWmfRlAuHyQuBPzObWFI+QMfvF2UDClgs/oxOPi+EpcuGMrFjMTY
            5Md7BFKxygL9OrlFelVOPl5JMd5GYb/2NGSMonyO8agSE/y8leFanDTp7jXaDzmA
            i+hry4FLCTFGptWhmM3PtHl1BJY5RiBgbsDtRWWDwY8MpxXzDd4cMfD4l4GZK5eF
            xKajyjxmVN9eYv9hoM0niHgwX6JdEuWUeTLRaLQx+gqYVA55kUBCyr8sJ5t6QaIH
            3zjpCB77sKNPWo1eog/27IrIjwVgGGeoEYlqqI5sA6js29NZeX3fuR9be6pJW9Y/
            la/JpE3UtAL8F/NPrPOn4g3XxtpCIYd0qD1c8xkjfHJdio46x0LLAGY8p58FV2xK
            5i+6CKffe5dVWYfNHNRQeztwzQDKaiRw9UmsQc4M4KARzngoGygHhnqyVL/DsPVr
            c7UAEHy+zSWcerHoouLyE7Zgfj80aB02Gl0RbH7R2+wUgZqV2d/gof6gnUNvbGq8
            JtDewGUw8D77ZZAfLopD+ODxEbuWLfLW5ycMgu0bLJahEG02fnIikf2h0Pp6z+/S
            XAG0egqWkWxgkpxbQUsEQ6awx759fyiPAQAUOj+tPcW6qiT1xTpnIGL2tGqxN3A/
            H9s2RAjJ+E+Js8Z3OjOdQ6uwho88/zQD4ZZ0vyoip+Ln2qvI4IDSWDiSHJNU
            =9JwE
            -----END PGP MESSAGE-----
          fp: 6A26EC621F5482FA6A638E2A02E879357525DBCB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
