---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - home.yaml
  - longhorn-system.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - networking.yaml
  - pihole.yaml
  - unbound.yaml
  - velero.yaml
